### ISSUE TITLE
Training custom model?

### ISSUE THREAD

**Issue by Zarxrax** [hustvl/Matte-Anything#11]
Is it possible to train on my own dataset? And is there any basic instruction for doing so?
Thanks!

**Comment by JingfengYao** [comment]
Matte Anything is training-free. If you want to train a matting model, try our foundation work [ViTMatte](https://github.com/hustvl/ViTMatte).

**Comment by JingfengYao** [comment]
Matte Anything is training-free. If you want to train a matting model, you could try our foundation work [ViTMatte](https://github.com/hustvl/ViTMatte).
