### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by PangQiangwut** [hustvl/Matte-Anything#15]
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by afly36-swordsman** [comment]
I've run into this problem as well!!
