### ISSUE TITLE
Automatic object detection

### ISSUE THREAD

**Issue by LukaGiorgadze** [hustvl/Matte-Anything#19]
Is there a way to automatically detect objects and remove the background? This way, we can use it as a library and not just from the UI.

**Comment by JingfengYao** [comment]
Sorry, I am afraid it can't.

**Comment by kexul** [comment]
Take a look at GroundingDINO, and combine it with this project.

**Comment by kexul** [comment]
Sorry, I just find that the README has reference GroundingDINO. I'm quite confusing why it can't now...
