### ISSUE TITLE
Incorrect dependency of requirements：gradio

### ISSUE THREAD

**Issue by TonyDua** [hustvl/Matte-Anything#20]
In the requirements.txt file, it is written:
```
torch==2.0.0
torchvision
tensorboard
timm==0.5.4
opencv-python==4.5.3.56
setuptools==58.2.0
easydict
wget
scikit-image
gradio
fairscale
```

Firstly, opencv-python==4.5.3.56 fails to compile in a Windows conda virtual environment with Python version 3.9.19 and CUDA version 11.8. 
But executing ‘pip install opencv-python’ directly solves the problem.

Secondly, pip install gradio in the aforementioned environment version, installs version 4.26.0 by default. Executing python matte_anything.py results in the following error:

```
Traceback (most recent call last):
  File "C:\Matte-Anything\matte_anything.py", line 309, in <module>
    with gr.Row().style(equal_height=True):
         ^^^^^^^^^^^^^^
AttributeError: 'Row' object has no attribute 'style'
IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
```

So, I uninstalled gradio and installed the latest version 4.29.0, but the problem persisted. Since there is no mention of the gradio version in your readme.md, after googling, I found a similar issue in another GitHub repository, suggesting the use of version 3.50.0. Therefore, I switched to gradio version 3.50.0.

Thank goodness, it finally executed, and the webpage opened. However, when selecting foreground and background points, I noticed that clicking on the image area had no effect, and a large number of errors appeared in the terminal.

![image](https://github.com/hustvl/Matte-Anything/assets/47080615/6903f853-3d6f-4de3-b2c7-3507130950fb)

So, I'd like to ask which version of gradio and Python you are using. Thank you again for your hard work. I really want to try it out, please help!

**Comment by YeL6** [comment]
> In the requirements.txt file, it is written:
> 
> ```
> torch==2.0.0
> torchvision
> tensorboard
> timm==0.5.4
> opencv-python==4.5.3.56
> setuptools==58.2.0
> easydict
> wget
> scikit-image
> gradio
> fairscale
> ```
> 
> Firstly, opencv-python==4.5.3.56 fails to compile in a Windows conda virtual environment with Python version 3.9.19 and CUDA version 11.8. But executing ‘pip install opencv-python’ directly solves the problem.
> 
> Secondly, pip install gradio in the aforementioned environment version, installs version 4.26.0 by default. Executing python matte_anything.py results in the following error:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Matte-Anything\matte_anything.py", line 309, in <module>
>     with gr.Row().style(equal_height=True):
>          ^^^^^^^^^^^^^^
> AttributeError: 'Row' object has no attribute 'style'
> IMPORTANT: You are using gradio version 4.26.0, however version 4.29.0 is available, please upgrade.
> ```
> 
> So, I uninstalled gradio and installed the latest version 4.29.0, but the problem persisted. Since there is no mention of the gradio version in your readme.md, after googling, I found a similar issue in another GitHub repository, suggesting the use of version 3.50.0. Therefore, I switched to gradio version 3.50.0.
> 
> Thank goodness, it finally executed, and the webpage opened. However, when selecting foreground and background points, I noticed that clicking on the image area had no effect, and a large number of errors appeared in the terminal.
> 
> ![image](https://private-user-images.githubusercontent.com/47080615/336426594-6903f853-3d6f-4de3-b2c7-3507130950fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1ODA4MzQsIm5iZiI6MTcxNzU4MDUzNCwicGF0aCI6Ii80NzA4MDYxNS8zMzY0MjY1OTQtNjkwM2Y4NTMtM2Q2Zi00ZGUzLWIyYzctMzUwNzEzMDk1MGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDA5NDIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmOWQyNDc0MmRmZDdjNTYyZGI1ZGU1NjRkMmJlMmYzYTE1YjZiYzc5OTFmZDQ2NGZjOGY5ZjZjZjc3ZTU3OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PtyDU4lMlVzNE9-7pVqeInhfp9BWFOmBUoy5KCscz0k)
> 
> So, I'd like to ask which version of gradio and Python you are using. Thank you again for your hard work. I really want to try it out, please help!

Thank you for your interest in our work! We appreciate your question!

About the code you gave us, we believe the issue might be due to an update in the gradio version. I checked the original code, which uses version 3.34.0. You might try using `pip install gradio==3.34.0` to match the environment with the original setup.

I hope this works for you! If you have any other questions, we will be sure to continue to help you.

**Comment by TonyDua** [comment]
@YeL6 
Thank you for your guidance!

I also tried updating the relevant code in `matte_anything.py` to meet the requirements of the latest gradio version. The main modification was changing with` gr.Row().style(equal_height=True): `to` gr.Row()`., as gradio removed the style attribute. Additionally, I removed `gr.input` and changed the `default` variable of all controls to `value`. Now, this script runs well in the latest gradio version.

I'm not sure if your team has any compatibility plans for the latest version of gradio, so I didn't rush to submit a PR.

1.According to @YeL6's reply, execute the following commands:
```
pip uninstall gradio
pip install gradio==3.34.0
```
2.If you want to use the latest version of gradio:
Follow the above method to modify` matte_anything.py`. I'm sorry GitHub doesn't allow inserting .py files in replies, so I can't paste it here.

Finally, I suggest considering updating the code to be compatible with the latest version of gradio, or allowing me to submit a PR. Thank you!

**Comment by YeL6** [comment]
@TonyDua 
Thank you very much for your contribution! This will be of great help to the users of matte-anything!

On the other hand, projects can indeed encounter issues due to updates of different packages. To address this, we currently plan to specify the corresponding package versions in the `requirements.txt` file. In the future, we will strive to provide more comprehensive updates. Thank you for your attention.

**Comment by TonyDua** [comment]
@YeL6
Thank you! Looking forward to future updates!
