### ISSUE TITLE
After running the code, when an image is inputted on the web interface and clicked, an error is displayed

### ISSUE THREAD

**Issue by 1013764208** [hustvl/Matte-Anything#22]
After running the code, when an image is inputted on the web interface and clicked, an error is displayed，Tried many times, reinstalled several times, but errors still occurred.
<img width="1302" alt="Snipaste_2024-06-09_23-36-41" src="https://github.com/hustvl/Matte-Anything/assets/55837685/4f77b7ae-b576-4c05-830a-d6e666d66c08">

**Comment by YeL6** [comment]
> After running the code, when an image is inputted on the web interface and clicked, an error is displayed，Tried many times, reinstalled several times, but errors still occurred. <img alt="Snipaste_2024-06-09_23-36-41" width="1302" src="https://private-user-images.githubusercontent.com/55837685/337985392-4f77b7ae-b576-4c05-830a-d6e666d66c08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwODk0NDAsIm5iZiI6MTcxODA4OTE0MCwicGF0aCI6Ii81NTgzNzY4NS8zMzc5ODUzOTItNGY3N2I3YWUtYjU3Ni00YzA1LTgzMGEtZDZlNjY2ZDY2YzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA2NTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3YjE5MjI4MGY3Mjk1YjliODZhMTI2OTkzMDIwNzI1ODkyNTE0YWJjYjcyYjlhMzI2YjFjMjM1YTM1MWU0Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nbdOpgZC7ZqG_6-kp9JFhHjlTOvCXK3P5-0bEzyjDI8">

Could you please provide more information about the error you're encountering? This will help me offer a more accurate solution.

**Comment by 1013764208** [comment]
It was done by following the steps of the quick installation guide, sequentially installing the required dependencies, then proceeding with the installation of pre-trained models. After launching web , upon attempting to load an image, an error was encountered. I've been running this on autodl. If necessary, I can provide you with SSH access and the password.

**Comment by YeL6** [comment]
@1013764208 
Are you encountering any errors when running the program? After uploading the image and executing the process, could you please check your terminal for any error messages?

**Comment by 1013764208** [comment]
没有任何报错信息，只是在 web 显示 error；我尝试 debug 调试，终端也没有打印任何错误

**Comment by yaoyuan13** [comment]
> After running the code, when an image is inputted on the web interface and clicked, an error is displayed，Tried many times, reinstalled several times, but errors still occurred. <img alt="Snipaste_2024-06-09_23-36-41" width="1302" src="https://private-user-images.githubusercontent.com/55837685/337985392-4f77b7ae-b576-4c05-830a-d6e666d66c08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTY5NzEsIm5iZiI6MTcxODYxNjY3MSwicGF0aCI6Ii81NTgzNzY4NS8zMzc5ODUzOTItNGY3N2I3YWUtYjU3Ni00YzA1LTgzMGEtZDZlNjY2ZDY2YzA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA5MzExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2YjE1Mzc0OTljY2U0ZDhiNGZmOGE4ZjRlYWFiZmJkY2U3NzEzMWVhNjNhNTg1NWUzNjU0ZjZmYjQ2MTdjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h6A4SwNAQobp5uFDEU5CaeV2w8ngCyXc2VOEpfI6oVY">

I also encounter this error issue, with no error msg in the terminal, have you solved it?

**Comment by Lineves7** [comment]
how to solve this problem?
