### ISSUE TITLE
about   install  windows,  have a error?

### ISSUE THREAD

**Issue by zhanghongyong123456** [hustvl/Matte-Anything#4]
![image](https://github.com/hustvl/Matte-Anything/assets/48466610/556fe2ae-523b-4392-8746-92ac3bd4ab1b)

**Comment by YeL6** [comment]
> ![image](https://user-images.githubusercontent.com/48466610/246028176-556fe2ae-523b-4392-8746-92ac3bd4ab1b.png)

**Comment by YeL6** [comment]
Could you please provide more info? It sounds strange since we could not reproduce your error.

**Comment by YeL6** [comment]
> ![image](https://user-images.githubusercontent.com/48466610/246028176-556fe2ae-523b-4392-8746-92ac3bd4ab1b.png)

Could you please provide more info? It sounds strange since we could not reproduce your error.

**Comment by zhanghongyong123456** [comment]
> > ![image](https://user-images.githubusercontent.com/48466610/246028176-556fe2ae-523b-4392-8746-92ac3bd4ab1b.png)
> 
> Could you please provide more info? It sounds strange since we could not reproduce your error.

# packages in environment at H:\Anaconda3\envs\matte-anything:
#
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
aiofiles                  23.1.0                   pypi_0    pypi
aiohttp                   3.8.4                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    5.0.1                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.7.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     23.1.0                   pypi_0    pypi
black                     21.4b2                   pypi_0    pypi
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.05.30           haa95532_0    defaults
cachetools                5.3.1                    pypi_0    pypi
certifi                   2022.12.7                pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.1                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
contourpy                 1.1.0                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.35                  pypi_0    pypi
detectron2                0.6                       dev_0    <develop>
exceptiongroup            1.1.1                    pypi_0    pypi
fairscale                 0.4.13                   pypi_0    pypi
fastapi                   0.97.0                   pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.9.0                    pypi_0    pypi
fonttools                 4.40.0                   pypi_0    pypi
frozenlist                1.3.3                    pypi_0    pypi
fsspec                    2023.6.0                 pypi_0    pypi
future                    0.18.3                   pypi_0    pypi
google-auth               2.20.0                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
gradio                    3.34.0                   pypi_0    pypi
gradio-client             0.2.7                    pypi_0    pypi
groundingdino             0.1.0                     dev_0    <develop>
grpcio                    1.56.0rc2                pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  0.17.2                   pypi_0    pypi
httpx                     0.24.1                   pypi_0    pypi
huggingface-hub           0.15.1                   pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
iopath                    0.1.9                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jsonschema                4.17.3                   pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_0    defaults
lightning-utilities       0.8.0                    pypi_0    pypi
linkify-it-py             2.0.2                    pypi_0    pypi
markdown                  3.4.3                    pypi_0    pypi
markdown-it-py            2.2.0                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1                    pypi_0    pypi
mdit-py-plugins           0.3.3                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
multidict                 6.0.4                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
numpy                     1.24.1                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   3.0.8                h2bbff1b_0    defaults
orjson                    3.9.1                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pandas                    2.0.2                    pypi_0    pypi
pathspec                  0.11.1                   pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pip                       23.1.2          py310haa95532_0    defaults
platformdirs              3.5.3                    pypi_0    pypi
portalocker               2.7.0                    pypi_0    pypi
protobuf                  4.23.3                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
pycocotools               2.0.6                    pypi_0    pypi
pydantic                  1.10.9                   pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.15.1                   pypi_0    pypi
pyparsing                 3.1.0b2                  pypi_0    pypi
pyrsistent                0.19.3                   pypi_0    pypi
python                    3.10.11              he1021f5_3    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python-multipart          0.0.6                    pypi_0    pypi
pytorch-lightning         2.0.3                    pypi_0    pypi
pytz                      2023.3                   pypi_0    pypi
pywin32                   306                      pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
regex                     2023.6.3                 pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
safetensors               0.3.1                    pypi_0    pypi
segment-anything          1.0                      pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
setuptools                67.8.0          py310haa95532_0    defaults
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0    defaults
starlette                 0.27.0                   pypi_0    pypi
supervision               0.6.0                    pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboard               2.13.0                   pypi_0    pypi
tensorboard-data-server   0.7.1                    pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
timm                      0.9.2                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0    defaults
tokenizers                0.13.3                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     2.0.0+cu117              pypi_0    pypi
torchaudio                2.0.1+cu117              pypi_0    pypi
torchmetrics              0.11.4                   pypi_0    pypi
torchvision               0.15.1+cu117             pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
transformers              4.30.2                   pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2023.3                   pypi_0    pypi
uc-micro-py               1.0.2                    pypi_0    pypi
urllib3                   1.26.13                  pypi_0    pypi
uvicorn                   0.22.0                   pypi_0    pypi
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
websockets                11.0.3                   pypi_0    pypi
werkzeug                  2.3.6                    pypi_0    pypi
wheel                     0.38.4          py310haa95532_0    defaults
xz                        5.4.2                h8cc25b3_0    defaults
yacs                      0.1.8                    pypi_0    pypi
yapf                      0.40.0                   pypi_0    pypi
yarl                      1.9.2                    pypi_0    pypi
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_0    defaults

**Comment by zhanghongyong123456** [comment]
> > ![image](https://user-images.githubusercontent.com/48466610/246028176-556fe2ae-523b-4392-8746-92ac3bd4ab1b.png)
> 
> Could you please provide more info? It sounds strange since we could not reproduce your error.

I've already fixed this problem because of the detectron2 version issue  , need to pull the latest(main) code and code it, not the v0.6 release(https://github.com/facebookresearch/detectron2/releases/tag/v0.6),

https://github.com/hustvl/ViTMatte/issues/6

**Comment by JingfengYao** [comment]
@zhanghongyong123456  Awesome! 👍 👍
