### ISSUE TITLE
Bad matting result

### ISSUE THREAD

**Issue by sun631998316** [hustvl/Matte-Anything#9]
I have tested several pictures, and the result of matting in the edge area is not good, may I ask what is the reason.![image](https://github.com/hustvl/Matte-Anything/assets/27120910/aff7c657-ac00-499d-b482-ffe1a73674b7)
![image](https://github.com/hustvl/Matte-Anything/assets/27120910/db1e16de-24bc-4d23-ae2a-2fa954c3b3dc)

**Comment by JingfengYao** [comment]
1. You could try to change the hyperparameters of Matte-Anything.
2. Matte Anything may suffer from performance degradation when generalized to some complicated scenes since the limitation of matting training datasets.

**Comment by anilsathyan7** [comment]
This seems to be an issue even with simple images with plain background. Is it due to the ViTMatte model?
